### ISSUE TITLE
баг с меню

### ISSUE THREAD

**Issue by lol1d1** [destroydevs/primeseller#10]
в последней версии плагина (до этого юзал 2.3.6) столкнулся с проблемой: при установке размера меню 45, слоты 41-44 начинают выдавать сообщение о том, что недостаточно предметов для продажи, хотя они сделаны как заполнители (divider). при этом остальные заполнители работают нормально

![Image](https://github.com/user-attachments/assets/00c3f21c-85dd-4e73-ac24-199240e2fc07)

прикрепляю menu.yml

```
title: 'Скупщик' # тайтл в меню
size: 45 # кол-во слотов

sell-inventory:
  material: 'CHEST'
  model-data: 0
  name: '#01b7f2Продать инвентарь'
  lore:
    - ''
    - '§x§a§3§a§a§b§6Автоматически продаст все'
    - '§x§a§3§a§a§b§6предметы, которые принимает'
    - '§x§a§3§a§a§b§6скупщик, из вашего инвентаря.'
    - '§x§a§3§a§a§b§6В приоритете - категория с'
    - '§x§a§3§a§a§b§6лимитом.'
    - ''
    - '§x§f§b§c§f§2§8Нажмите, чтобы продать'
  slots:
    - 40
    
exit:
  material: BARRIER
  model-data: 0
  name: '#d92625Закрыть ✕'
  commands:
    - '[close]'
  slots: # счет с 0
    - 36

countdown:
  material: 'basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWUwMTFhYWM4MTcyNTlmMmI0OGRhM2U1ZWYyNjYwOTQ3MDM4NjY2MDhiM2Q3ZDE3NTQ0MzJiZjI0OWNkMjIzNCJ9fX0='
  model-data: 0
  name: '#01b7f2Информация по скупщику'
  lore:
    - ''
    - '#a3aab6Скупщик - персонаж, который готов'
    - '#a3aab6покупать ресурсы с ваших ферм!'
    - '#a3aab6С каждой последующей продажей,'
    - '#a3aab6он понижает цены.'
    - ''
    - '#a3aab6Существует две категории скупки:'
    - ' &8▪ #fbecb1С лимитом:  &8←'
    - '   #a3aab6Цены выше, но кол-во'
    - '   #a3aab6предметов ограничено!'
    - '   #a3aab6Обновление: #b3ca8dкаждый час'
    - '   #a3aab6След. обновление: #b3ca8dчерез %lim-time%'
    - ''
    - ' &8▪ #fbecb1Без лимита:  &8→'
    - '   #a3aab6Цены ниже, но кол-во'
    - '   #a3aab6предметов не ограничено!'
    - '   #a3aab6Обновление: #b3ca8dкаждые 3 часа'
    - '   #a3aab6След. обновление: #b3ca8dчерез %unlim-time%'
  slots:
    - 4
    

lim-items:
  lore:
    - ''
    - ' &fЦена за #fbecb1х1: &e%price-x1%⛂ #a3aab6(ЛКМ)'
    - ' &fЦена за #fbecb1х64: &e%price-x64%⛂ #a3aab6(ПКМ)'
    - ' &fЦена за #fbecb1всё: &e%price-all%⛂ #a3aab6(Shift + ЛКМ)'
    - ''
    - '#a3aab6Лимиты:'
    - ' &8▪ #a3aab6По категории: #b3ca8d%sell% из %max%'
    - ' &8▪ #a3aab6По предмету: #b3ca8d%sell-items% из %max-items%'
  slots: # счет с 0
    - 9
    - 10
    - 11
    - 12
    - 18
    - 19
    - 20
    - 21
    - 27
    - 28
    - 29
    - 30

unlim-items:
  lore:
    - ''
    - ' &fЦена за #fbecb1х1: &e%price-x1%⛂ #a3aab6(ЛКМ)'
    - ' &fЦена за #fbecb1х64: &e%price-x64%⛂ #a3aab6(ПКМ)'
    - ' &fЦена за #fbecb1всё: &e%price-all%⛂ #a3aab6(Shift + ЛКМ)'
    - ''
    - '#a3aab6Лимиты:'
    - ' &8▪ #a3aab6По категории: #b3ca8dнет'
    - ' &8▪ #a3aab6По предмету: #b3ca8dнет'
  slots: # счет с 0
    - 14
    - 15
    - 16
    - 17
    - 23
    - 24
    - 25
    - 26
    - 32
    - 33
    - 34
    - 35

divider:
  background:
    material: BLACK_STAINED_GLASS_PANE
    model-data: 0
    name: '&7'
    slots: # счет с 0
      - 39
      - 38
      - 37
      - 41
      - 42
      - 43
      - 44
      - 13
      - 22
      - 31
  limit:
    material: BLACK_STAINED_GLASS_PANE
    model-data: 0
    name: '&8↓ &7Лимит.'
    slots: # счет с 0
      - 0
      - 1
      - 3
      - 2
  unlimit:
    material: BLACK_STAINED_GLASS_PANE
    model-data: 0
    name: '&8↓ &7Безлимит.'
    slots: # счет с 0
      - 5
      - 6
      - 7
      - 8
```
